# Generated by Django 2.0 on 2018-01-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='titulo',
            field=models.CharField(default='una consulta cualquiera', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='consulta',
            field=models.TextField(max_length=300),
        ),
    ]
