# Generated by Django 2.0 on 2018-01-24 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Vota', '0004_opcion_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcion',
            name='autor',
        ),
        migrations.AddField(
            model_name='votacion',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
