# Generated by Django 2.0 on 2018-01-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vota', '0006_invitacion_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votacion',
            name='opcion',
        ),
    ]
