# Generated by Django 2.0 on 2018-01-31 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vota', '0007_remove_votacion_opcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacion',
            name='opcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Vota.Opcion'),
            preserve_default=False,
        ),
    ]
