# Generated by Django 2.0 on 2018-02-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vota', '0009_remove_opcion_votos'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='votaciones',
            field=models.IntegerField(default=0),
        ),
    ]
