# Generated by Django 2.0 on 2018-02-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vota', '0010_opcion_votaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votacion',
            name='consulta',
        ),
    ]
