# Generated by Django 2.0 on 2018-02-14 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vota', '0012_remove_opcion_votaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacion',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
